version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    working_directory: ~/cneuromod-test-dypac
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run
          command: |
            pip install -r requirements.txt
            pip install pytest
      - run:
          command: |
            pytest dypac/test_bascpp.py
          name: Test_bascppp
      - run:
          command: |
            pytest dypac/test_dypac.py
          name: Test_dypac
      - store_test_results:
          path: test-results

workflows:
  main:
    jobs:
      - build-and-test
